version: '3.8'

services:
  tmdb-addon:
    build: .
    container_name: tmdb-addon
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: tmdb-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5